### PR TITLE
Normalize package name

### PR DESCRIPTION
**Pull request by takaswie**
The first field of AC_INIT has an effect for name of generated archive name and header directory. This commit normalize them, while hinawa is still used for GObject Introspection.

### CODE REVIEW

**Comment by takaswie** [comment]
Oops, this patchset is a bit confusing... Please review the last patch (db17704b8bfd). The rest is already applied to my master.

**Comment by kenhys** [comment]
https://github.com/kenhys/libhinawa/commit/db17704b8bfd138d9a6eff187a56e7691009a351 LGTM.

**Comment by takaswie** [comment]
Applied, thanks.
https://github.com/takaswie/libhinawa/commit/db17704b8bfd138d9a6eff187a56e7691009a351

Please PR again for your 72b2146bc69c46d3fdfd7c8fc295744db68d0612.

**Comment by kenhys** [comment]
The feature is already merged by another PR.

**Pull request merged**
